### ISSUE TITLE
Version bump to 0.6.2

### ISSUE THREAD

**Issue by silverhook** [ubuntuvibes/Debs#2]
0.6.1 and 0.6.2 are out already. It’d be lovely if you would package the new versions as well.

And many thanks for writing the package in the first place :joy_cat:

**Comment by ubuntuvibes** [comment]
You can get new packages from https://launchpad.net/~rikmills/+archive/ubuntu/latte-dock.

**Comment by silverhook** [comment]
Brilliant, thank you :)
